# Generated by Django 2.0.6 on 2018-06-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('bento_type', models.CharField(choices=[('L', 'Light'), ('B', 'Balance')], default='L', max_length=1)),
                ('cuisine', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('remain', models.IntegerField()),
                ('bento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Bento')),
            ],
        ),
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('line_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('grade', models.CharField(blank=True, choices=[('G', 'Graduate'), ('U', 'UnderGraduate'), ('P', 'Professor'), ('O', 'Other')], max_length=1)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('unfollow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DailyMenu')),
                ('line_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.LineProfile')),
            ],
        ),
    ]
