# Generated by Django 2.0.6 on 2018-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_bento_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bento',
            name='photo',
            field=models.ImageField(upload_to='bento_imgs/'),
        ),
    ]
