# Generated by Django 2.0.6 on 2018-06-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180616_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bento',
            name='description',
        ),
    ]
