# Generated by Django 2.0.6 on 2018-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_bento_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bento_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocationaLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField()),
                ('limitation', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='bento',
        ),
        migrations.RemoveField(
            model_name='order',
            name='daily_menu',
        ),
        migrations.AddField(
            model_name='bento',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.Bento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bento',
            name='bento_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.BentoType'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Job'),
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
        migrations.AddField(
            model_name='locationalimitation',
            name='bento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Bento'),
        ),
        migrations.AddField(
            model_name='locationalimitation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Location'),
        ),
        migrations.AddField(
            model_name='distributionplace',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='distribution_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.DistributionPlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Location'),
            preserve_default=False,
        ),
    ]
