# Generated by Django 2.0.6 on 2018-06-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180617_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='bento',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
