# Generated by Django 2.0.6 on 2018-06-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_bento_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='bento',
            name='price',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
