# Generated by Django 2.0.6 on 2018-06-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20180617_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
