# Generated by Django 2.0.6 on 2018-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_lineprofile_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineprofile',
            old_name='picture_url',
            new_name='line_picture_url',
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='line_status_message',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='arealimitation',
            unique_together={('bento', 'area')},
        ),
    ]
