# Generated by Django 2.0.6 on 2018-06-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20180618_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Job', verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='狀態'),
        ),
    ]
