# Generated by Django 2.0.6 on 2018-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20180618_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='line_status_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
