# Generated by Django 2.0.6 on 2018-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20180618_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='line_picture_url',
            field=models.URLField(verbose_name='Line照片網址'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='line_status_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Line狀態訊息'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='unfollow',
            field=models.BooleanField(default=False, verbose_name='封鎖'),
        ),
    ]
