# Generated by Django 2.0.6 on 2018-07-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_lineprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=120, verbose_name='價格'),
        ),
    ]
