# Generated by Django 2.0.6 on 2018-07-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
