# Generated by Django 2.0.6 on 2018-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineprofile',
            name='friend',
            field=models.BooleanField(default=True, verbose_name='好友'),
        ),
    ]
