# Generated by Django 2.0.6 on 2018-07-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_lineprofile_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False, verbose_name='已領取'),
        ),
    ]
