# Generated by Django 2.0.6 on 2018-08-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPlimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_limitation', models.IntegerField(verbose_name='上限個數')),
                ('dp_remain', models.IntegerField(verbose_name='剩於個數')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Area', verbose_name='地區')),
                ('bento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Bento', verbose_name='飯盒')),
                ('distribution_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DistributionPlace', verbose_name='發放地點')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dplimitation',
            unique_together={('bento', 'area', 'distribution_place')},
        ),
    ]
