# Generated by Django 2.0.6 on 2018-09-13 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20180820_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplace',
            name='end_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='結束時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionplace',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='發放地點圖片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionplace',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default=None, verbose_name='開始時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionplace',
            name='thumbnail_url',
            field=models.URLField(default=None, verbose_name='發放地點縮圖'),
            preserve_default=False,
        ),
    ]
