# Generated by Django 2.0.6 on 2018-09-19 05:58

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20180914_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplace',
            name='img_url',
            field=models.ImageField(upload_to=order.models.dp_image_path_wrapper, verbose_name='發放地點圖片'),
        ),
    ]
