# Generated by Django 2.0.6 on 2018-09-19 06:07

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20180919_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplace',
            name='thumbnail_url',
            field=models.ImageField(upload_to=order.models.dp_thumbnail_image_path_wrapper, verbose_name='發放地點縮圖'),
        ),
    ]
