# Generated by Django 2.0.6 on 2018-09-19 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20180919_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionplace',
            name='end_time',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='distributionplace',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='開始時間'),
        ),
    ]
